### ISSUE TITLE
'update_ha_state' is deprecated

### ISSUE THREAD

**Issue by forkineye** [clach04/home-assistant-x10#4]
Noticed the following warning in my logs, just a heads up. Thanks for writing this!  I'm on the light_support branch and HA 0.47.1.
[homeassistant.helpers.entity] 'update_ha_state' is deprecated. Use 'schedule_update_ha_state' instead.

**Comment by clach04** [comment]
@forkineye thanks for the report, apologies for the delay. I added a quick-n-dirty solution that should preserve backwards compatibility.
