### ISSUE TITLE
AttributeError: 'X10Switch' object has no attribute 'update_ha_state'

### ISSUE THREAD

**Issue by dony71** [clach04/home-assistant-x10#5]
update HA 0.65.5 and get this ERROR

2018-03-19 22:57:07 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall switch.turn_on: entity_id=[‘switch.bedroom_ceiling_light’]>
Traceback (most recent call last):
File “/usr/local/lib/python3.5/site-packages/homeassistant/core.py”, line 1006, in _event_to_service_call
await service_handler.func(service_call)
File “/usr/local/lib/python3.5/site-packages/homeassistant/components/switch/init.py”, line 109, in async_handle_switch_service
await switch.async_turn_on()
File “/usr/local/lib/python3.5/asyncio/futures.py”, line 381, in iter
yield self # This tells Task to wait for completion.
File “/usr/local/lib/python3.5/asyncio/tasks.py”, line 310, in _wakeup
future.result()
File “/usr/local/lib/python3.5/asyncio/futures.py”, line 294, in result
raise self._exception
File “/usr/local/lib/python3.5/concurrent/futures/thread.py”, line 55, in run
result = self.fn(*self.args, **self.kwargs)
File “/root/.homeassistant/custom_components/switch/x10.py”, line 118, in turn_on
self.update_ha_state()
AttributeError: ‘X10Switch’ object has no attribute ‘update_ha_state’

**Comment by clach04** [comment]
@dony71 just saw this issue, sorry for delay in responding. Thanks for the stack trace, looks like you are using https://github.com/clach04/home-assistant-x10/blob/master/x10.py#L118 - I have to confess I'm not using master. I changed the default branch of this project earlier in the year (I can't recall when, I thought it was Feb 2018 but I'm not 100% sure), so you should see it by hitting https://github.com/clach04/home-assistant-x10/.

I'm currently running HA 0.62.1 with Python 3.5.3 under Hassbian with a component called x10_tng, this has the updated API calls (which should work with the later HA 0.65.5 release).

Can you try with the new default branch? If that works, I'll merge that into master. NOTE as it is named differently the component name needs an update. Older config will probably work with just that one change. Dimming of lamp modules works with this (e.g. with Amazon Alex).

**Comment by clach04** [comment]
Fixed in master (a while ago)
